name: Build and Dockerize

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - uses: actions/setup-python@v5
          with:
            python-version: '3.13' 

        - name: Install Python dependencies
          run: pip install -r requirements.txt

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '23'

        - name: Install NPM dependencies
          run: npm install

        - name: Build static web resources
          run: npm run build-css

        - name: Lint
          run: ruff check

        - name: Test
          run: python -m pytest . --cov=app

        - name: Build Docker image
          run: docker build .